name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    tags:
      - v*



jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      CI: true

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [12.x, 13.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
          npm run bootstrap
      - name: Lint
        run: |
          npm run lint --if-present
      - name: Build
        run: |
          npm run build --if-present -- --no-emit
      - name: Test
        run: |
          npm run test --if-present
